import json
import os
import logging
from typing import Any, Dict, Optional, Union, overload

from playwright.sync_api import (
    Browser,
    BrowserContext,
    Playwright,
    PlaywrightContextManager,
)
from typing_extensions import Literal

from lucid_browser.virtdisplay import VirtualDisplay

from .utils import launch_options, sync_attach_vd


class Lucid Empire(PlaywrightContextManager):
    """
    Wrapper around playwright.sync_api.PlaywrightContextManager that automatically
    launches a browser and closes it when the context manager is exited.
    """

    def __init__(self, fingerprint=None, **kwargs):
        """
        Initializes the Lucid Empire Sovereign Browser.
        
        Args:
            fingerprint (str): Path to the Golden Template JSON. 
                               MANDATORY. Randomization is disabled.
        """
        super().__init__()
        
        # 1. Enforce Template Existence (Fail-Closed)
        if fingerprint is None:
            raise ValueError(
                "LUCID CORE PANIC: No Golden Template provided. "
                "Randomization Protocols Disabled. You must provide a "
                "path to a validated 'Golden Template' JSON."
            )

        # 2. JSON Template Ingestion
        if isinstance(fingerprint, str):
            if not os.path.exists(fingerprint):
                raise FileNotFoundError(
                    f"LUCID PANIC: Template file not found at {fingerprint}"
                )
            
            try:
                with open(fingerprint, 'r') as f:
                    self.config = json.load(f)
            except json.JSONDecodeError:
                raise ValueError("LUCID PANIC: Corrupted Golden Template JSON.")
        else:
            # Support direct dictionary injection for testing/memory-only ops
            self.config = fingerprint

        # 3. Schema Validation (Prevent Leak by Omission)
        # These vectors MUST be present to override the host hardware.
        required_vectors = ['navigator', 'screen', 'webgl', 'fonts']
        for vector in required_vectors:
            if vector not in self.config:
                raise ValueError(
                    f"LUCID PANIC: Invalid Template Structure. "
                    f"Missing critical vector: {vector}"
                )

        # 4. Pass to Engine
        # We inject the validated config into the launch options.
        self.launch_options = kwargs
        self.launch_options['config'] = self.config
        self.browser: Optional[Union[Browser, BrowserContext]] = None

    def __enter__(self) -> Union[Browser, BrowserContext]:
        super().__enter__()
        self.browser = NewBrowser(self._playwright, **self.launch_options)
        return self.browser

    def __exit__(self, *args: Any):
        if self.browser:
            self.browser.close()
        super().__exit__(*args)


@overload
def NewBrowser(
    playwright: Playwright,
    *,
    from_options: Optional[Dict[str, Any]] = None,
    persistent_context: Literal[False] = False,
    **kwargs,
) -> Browser: ...


@overload
def NewBrowser(
    playwright: Playwright,
    *,
    from_options: Optional[Dict[str, Any]] = None,
    persistent_context: Literal[True],
    **kwargs,
) -> BrowserContext: ...


def NewBrowser(
    playwright: Playwright,
    *,
    headless: Optional[Union[bool, Literal['virtual']]] = None,
    from_options: Optional[Dict[str, Any]] = None,
    persistent_context: bool = False,
    debug: Optional[bool] = None,
    **kwargs,
) -> Union[Browser, BrowserContext]:
    """
    Launches a new browser instance for Lucid Empire given a set of launch options.

    Parameters:
        from_options (Dict[str, Any]):
            A set of launch options generated by `launch_options()` to use
        persistent_context (bool):
            Whether to use a persistent context.
        **kwargs:
            All other keyword arugments passed to `launch_options()`.
    """
    if headless == 'virtual':
        virtual_display = VirtualDisplay(debug=debug)
        kwargs['virtual_display'] = virtual_display.get()
        headless = False
    else:
        virtual_display = None

    if not from_options:
        from_options = launch_options(headless=headless, debug=debug, **kwargs)

    # Persistent context
    if persistent_context:
        context = playwright.firefox.launch_persistent_context(**from_options)
        return sync_attach_vd(context, virtual_display)

    # Browser
    browser = playwright.firefox.launch(**from_options)
    return sync_attach_vd(browser, virtual_display)
