import asyncio
import json
import os
import logging
from functools import partial
from typing import Any, Dict, Optional, Union, overload

from playwright.async_api import (
    Browser,
    BrowserContext,
    Playwright,
    PlaywrightContextManager,
)
from typing_extensions import Literal

from lucid_browser.virtdisplay import VirtualDisplay

from .utils import async_attach_vd, launch_options


class AsyncLucid Empire(PlaywrightContextManager):
    """
    Wrapper around playwright.async_api.PlaywrightContextManager that automatically
    launches a browser and closes it when the context manager is exited.
    """

    def __init__(self, fingerprint=None, **kwargs):
        """
        Initializes the Lucid Empire Sovereign Browser (Async).
        
        Args:
            fingerprint (str): Path to the Golden Template JSON. 
                               MANDATORY. Randomization is disabled.
        """
        super().__init__()
        
        # 1. Enforce Template Existence (Fail-Closed)
        if fingerprint is None:
            raise ValueError(
                "LUCID CORE PANIC: No Golden Template provided. "
                "Randomization Protocols Disabled. You must provide a "
                "path to a validated 'Golden Template' JSON."
            )

        # 2. JSON Template Ingestion
        if isinstance(fingerprint, str):
            if not os.path.exists(fingerprint):
                raise FileNotFoundError(
                    f"LUCID PANIC: Template file not found at {fingerprint}"
                )
            
            try:
                with open(fingerprint, 'r') as f:
                    self.config = json.load(f)
            except json.JSONDecodeError:
                raise ValueError("LUCID PANIC: Corrupted Golden Template JSON.")
        else:
            # Support direct dictionary injection for testing/memory-only ops
            self.config = fingerprint

        # 3. Schema Validation (Prevent Leak by Omission)
        required_vectors = ['navigator', 'screen', 'webgl', 'fonts']
        for vector in required_vectors:
            if vector not in self.config:
                raise ValueError(
                    f"LUCID PANIC: Invalid Template Structure. "
                    f"Missing critical vector: {vector}"
                )

        # 4. Pass to Engine
        self.launch_options = kwargs
        self.launch_options['config'] = self.config
        self.browser: Optional[Union[Browser, BrowserContext]] = None

    async def __aenter__(self) -> Union[Browser, BrowserContext]:
        _playwright = await super().__aenter__()
        self.browser = await AsyncNewBrowser(_playwright, **self.launch_options)
        return self.browser

    async def __aexit__(self, *args: Any):
        if self.browser:
            await self.browser.close()
        await super().__aexit__(*args)


@overload
async def AsyncNewBrowser(
    playwright: Playwright,
    *,
    from_options: Optional[Dict[str, Any]] = None,
    persistent_context: Literal[False] = False,
    **kwargs,
) -> Browser: ...


@overload
async def AsyncNewBrowser(
    playwright: Playwright,
    *,
    from_options: Optional[Dict[str, Any]] = None,
    persistent_context: Literal[True],
    **kwargs,
) -> BrowserContext: ...


async def AsyncNewBrowser(
    playwright: Playwright,
    *,
    headless: Optional[Union[bool, Literal['virtual']]] = None,
    from_options: Optional[Dict[str, Any]] = None,
    persistent_context: bool = False,
    debug: Optional[bool] = None,
    **kwargs,
) -> Union[Browser, BrowserContext]:
    """
    Launches a new browser instance for Lucid Empire given a set of launch options.

    Parameters:
        from_options (Dict[str, Any]):
            A set of launch options generated by `launch_options()` to use
        persistent_context (bool):
            Whether to use a persistent context.
        **kwargs:
            All other keyword arugments passed to `launch_options()`.
    """
    if headless == 'virtual':
        virtual_display = VirtualDisplay(debug=debug)
        kwargs['virtual_display'] = virtual_display.get()
        headless = False
    else:
        virtual_display = None

    if not from_options:
        from_options = await asyncio.get_event_loop().run_in_executor(
            None,
            partial(launch_options, headless=headless, debug=debug, **kwargs),
        )

    # Persistent context
    if persistent_context:
        context = await playwright.firefox.launch_persistent_context(**from_options)
        return await async_attach_vd(context, virtual_display)

    # Browser
    browser = await playwright.firefox.launch(**from_options)
    return await async_attach_vd(browser, virtual_display)
