// Mozilla User Preferences
/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1706160000);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1706160000);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1706160000);
user_pref("browser.bookmarks.max_backups", 15);
user_pref("browser.cache.disk.enable", true);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.offline.enable", true);
user_pref("browser.ctrlTab.recentlyUsedOrder", false);
user_pref("browser.download.folderList", 1);
user_pref("browser.download.useDownloadDir", true);
user_pref("browser.history.expiration.transient_current_quarter_count", 4775);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1672531200000);
user_pref("browser.laterrun.bookkeeping.sessionCount", 86);
user_pref("browser.newtab.privateAllowed", false);
user_pref("browser.newtab.preload", true);
user_pref("browser.onboarding.notification.lastDate", 1672531200000);
user_pref("browser.pageloader.msecs", 300);
user_pref("browser.privatebrowsing.autostart", false);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.max_tabs_undo", 10);
user_pref("browser.sessionstore.max_windows_undo", 3);
user_pref("browser.sessionstore.privacy_level", 0);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage", "about:home");
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("browser.startup.homepage_override.buildID", "20230105000000");
user_pref("browser.tabs.drawInTitlebar", true);
user_pref("browser.tabs.extraDragSpace", true);
user_pref("browser.tabs.inTitlebar", 1);
user_pref("browser.taskbar.previews.enable", true);
user_pref("browser.toolbars.bookmarks.visibility", "newtab");
user_pref("browser.urlbar.decaying.bucket_count", 10);
user_pref("browser.urlbar.decaying.frecency_multiplier", 0.975);
user_pref("browser.urlbar.decaying.halflife_days", 45);
user_pref("browser.urlbar.maxHistoricalSearchSuggestions", 0);
user_pref("browser.urlbar.suggest.bookmark", true);
user_pref("browser.urlbar.suggest.history", true);
user_pref("browser.urlbar.suggest.history.onlyTyped", false);
user_pref("browser.urlbar.suggest.openpage", true);
user_pref("browser.urlbar.suggest.searches", true);
user_pref("browser.urlbar.trending.featureGate", false);
user_pref("browser.urlbar.weather.featureGate", false);
user_pref("browser.urlbar.maxCharsForSearchSuggestions", 0);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1706246400000");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);

// ==================== ANTI-DETECTION HARDENING ====================
// WebRTC Leak Protection
user_pref("media.peerconnection.enabled", false);
user_pref("media.peerconnection.ice.default_address_only", true);
user_pref("media.peerconnection.ice.no_host", true);
user_pref("media.peerconnection.turn.disable", true);

// Canvas Fingerprinting Protection
user_pref("privacy.resistFingerprinting", true);
user_pref("privacy.resistFingerprinting.letterboxing", true);
user_pref("browser.display.os-zoom-behavior", 2);

// Plugin & WebGL Protection
user_pref("webgl.disabled", true);
user_pref("dom.plugins.enabled", false);

// Geolocation Spoofing
user_pref("geo.enabled", false);
user_pref("geo.provider.use_corelocation", false);

// DNS-over-HTTPS (DoH) Hardening
user_pref("network.trr.mode", 3);
user_pref("network.trr.uri", "https://dns.cloudflare.com/dns-query");
user_pref("network.security.esni.enabled", true);

// Disable Telemetry & Studies
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.normandy.enabled", false);
user_pref("app.update.auto", false);

// Disable Pocket & Sync
user_pref("extensions.pocket.enabled", false);
user_pref("services.sync.enabled", false);
user_pref("identity.fxaccounts.enabled", false);

// HTTPS-Only Mode
user_pref("dom.security.https_only_mode", true);
user_pref("dom.security.https_only_mode_send_http_background_request", false);

// Referrer Policy
user_pref("network.http.referer.XOriginPolicy", 2);
user_pref("network.http.referer.trimmingPolicy", 2);

// Third-Party Cookie Blocking
user_pref("network.cookie.cookieBehavior", 4);
user_pref("network.cookie.sameSite.laxByDefault", true);
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.socialtracking.enabled", true);

// Disable Mixed Content
user_pref("security.mixed_content.block_active_content", true);
user_pref("security.mixed_content.block_display_content", true);

// Disable Password Manager (use commerce_vault.json instead)
user_pref("signon.rememberSignons", false);
user_pref("signon.autofillForms", false);

// Restrict JavaScript Shared Memory
user_pref("javascript.options.shared_memory", false);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1672531200000");
user_pref("distribution.searchplugins.defaultLocale", "en-US");
user_pref("dom.disable_beforeunload", false);
user_pref("dom.disable_unload_anim", false);
user_pref("dom.event.clipboardevents.enabled", true);
user_pref("dom.max_script_run_time", 30);
user_pref("dom.popup_allowed_events", "click dblclick mousedown pointerdown");
user_pref("dom.serviceWorkers.exemptFromPerDomainMax", true);
user_pref("dom.serviceWorkers.testing.enabled", true);
user_pref("extensions.activeThemeID", "firefox-compact-dark@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1706160000000);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230105000000");
user_pref("extensions.lastAppVersion", "109.0");
user_pref("extensions.lastPlatformVersion", "10.0");
user_pref("extensions.systemAddonSet", "{}");
user_pref("extensions.webextensions.uuids", "{}");
user_pref("gfx.canvas.azure.backends", "direct2d11,cairo");
user_pref("idle.lastDailyNotification", 1706160000000);
user_pref("intl.accept_languages", "en-US,en;q=0.9");
user_pref("intl.locale.requested", "en-US");
user_pref("layout.spellcheckDefault", 1);
user_pref("media.autoplay.default", 2);
user_pref("media.autoplay.enabled.user-gestures-needed", false);
user_pref("network.cookie.cookieBehavior", 0);
user_pref("network.cookie.lifetimePolicy", 0);
user_pref("network.dnsCacheExpiration", 60);
user_pref("network.http.keep-alive.timeout", 300);
user_pref("network.http.max-connections", 256);
user_pref("network.http.max-connections-per-server", 6);
user_pref("network.http.max-persistent-connections-per-server", 6);
user_pref("network.http.pipelining.ssl", false);
user_pref("network.http.spdy.enabled", true);
user_pref("network.http.spdy.enabled.http2", true);
user_pref("network.idletime.spy.enabled", true);
user_pref("network.manage-offline-status", true);
user_pref("network.proxy.no_proxies_on", "localhost, 127.0.0.1");
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1706160000000);
user_pref("places.history.expiration.transient_current_quarter_count", 3141);
user_pref("plugin.state.flash", 0);
user_pref("print.print_bgimages", false);
user_pref("print.print_bgcolors", false);
user_pref("print.print_edges", false);
user_pref("print.print_footercentered", "");
user_pref("print.print_footerleft", "&PT");
user_pref("print.print_footerright", "&D");
user_pref("print.print_headercentered", "");
user_pref("print.print_headerleft", "&T");
user_pref("print.print_headerright", "");
user_pref("print.print_in_color", true);
user_pref("print.print_margin_bottom", 0.5);
user_pref("print.print_margin_left", 0.5);
user_pref("print.print_margin_right", 0.5);
user_pref("print.print_margin_top", 0.5);
user_pref("print.print_orientation", 0);
user_pref("print.print_paper_data", 1);
user_pref("print.print_paper_height", 11);
user_pref("print.print_paper_width", 8.5);
user_pref("print.print_scaling", 1);
user_pref("print.print_shrink_to_fit", true);
user_pref("print.print_to_file", false);
user_pref("print.print_to_filename", "");
user_pref("print.printer_thermal.print_to_file", false);
user_pref("print.printer_thermal.print_to_filename", "");
user_pref("privacy.history.custom", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.socialtracking.enabled", true);
user_pref("reader.parse-on-load.enabled", true);
user_pref("security.dialog_enable_delay", 1000);
user_pref("security.enterprise_roots.enabled", false);
user_pref("security.fileuri.strict_origin_policy", true);
user_pref("security.insecure_connection_icon.enabled", true);
user_pref("security.insecure_connection_icon.pbmode.enabled", true);
user_pref("security.mixed_content.block_active_content", true);
user_pref("security.mixed_content.block_display_content", false);
user_pref("security.sandbox.content.level", 2);
user_pref("security.tls.version.max", 4);
user_pref("security.tls.version.min", 3);
user_pref("media.peerconnection.enabled", false);
user_pref("media.peerconnection.ice.default_address_only", true);
user_pref("dom.webdriver.enabled", false);
user_pref("dom.webdriver.chrome.enabled", false);
user_pref("webgl.disabled", true);
user_pref("network.trr.mode", 2);
user_pref("network.trr.uri", "https://cloudflare-dns.com/dns-query");
user_pref("dom.event.clipboardevents.enabled", false);
user_pref("privacy.resistFingerprinting", true);
user_pref("privacy.resistFingerprinting.letterboxing", true);
user_pref("services.sync.engine.addresses.available", true);
user_pref("services.sync.engine.creditcards.available", true);
user_pref("services.sync.nextSync", 0);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1706160000000);
user_pref("toolkit.cosmeticAnimations.enabled", true);
user_pref("toolkit.startup.last_success", 1706160000000);
user_pref("toolkit.telemetry.archive.enabled", false);
user_pref("toolkit.telemetry.bhrPing.enabled", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.firstShutdownPing.enabled", false);
user_pref("toolkit.telemetry.newProfilePing.enabled", false);
user_pref("toolkit.telemetry.shutdownPingSender.enabled", false);
user_pref("toolkit.telemetry.unified", false);
user_pref("toolkit.telemetry.updatePing.enabled", false);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
